#!/bin/bash
# Re-validate the shipped pipeline after five changes in twelve hours.
#
# WHY. Goal 3.1 was marked MET on runs from 2026-08-09 21:05. Publisher
# stripping landed on the single-pass path at 2026-08-10 03:17 - six hours
# later - and their logs confirm zero "Stripped publisher" lines. So three of
# the four books that met the goal were generated by a pipeline that no longer
# exists. The claim is stale, not necessarily wrong, and one run settles which.
#
# grimgar03 is the book to run because it exercises BOTH fixes at once:
# publisher stripping removes 26 back paragraphs of J-Novel Club advertising,
# while its front matter keeps the eight repeated titles that the
# faithful-duplicate fix has to carry. If the two interact badly, this is
# where it shows.
#
# Three outcomes, all useful: 100% again confirms the goal under the shipped
# code; fewer retries means the strip measurably helps; worse means a
# regression found before it ships.
#
# WAITS FOR THE GPU. The three-pass index18 arm is running. Two generators
# against one server took identical calls from 45 tok/s to 5.7 last night and
# cost 2h12m, so this blocks until nothing else is generating rather than
# starting alongside it.
set -uo pipefail
REPO=/home/fakemitch/pinokio/api/alexandria-audiobook2.git

# HOLD THE REAL LOCK INSTEAD OF GUESSING WHO IS RUNNING. The poll loop this
# replaces enumerated script names, so a GPU job nobody listed was invisible -
# `measure_respellings.py` held the card for seventeen hours on 2026-08-17 and
# appears in none of those lists. It also raced between "nothing is running"
# and "start mine". gpu_job.sh's flock does not care what the other job is
# called. Same idiom as run_chains/pdnc_context_evidence.sh; the sentinel is
# exported by gpu_job.sh, so this is safe when nested.
if [ "${ALEXANDRIA_GPU_LOCK_HELD:-0}" != 1 ]; then
    exec "$REPO/gpu_job.sh" "regression_after_pipeline_changes" \
        env ALEXANDRIA_GPU_LOCK_HELD=1 "$0" "$@"
fi
L="$REPO/ab_test_runtime/logs"
PY="$REPO/app/env/bin/python"
OUT="$REPO/ab_test_runtime/regression"
BACKUP="$L/config.json.regression_backup"
mkdir -p "$OUT"
cd "$REPO/app"

restore() {
    [ -f "$BACKUP" ] && command cp -f "$BACKUP" "$REPO/app/config.json"
}
trap restore EXIT INT TERM

# Wait for any other generator to finish. Checks for the process by exact
# script name, and never matches this script's own command line.

if ! curl -s -m 20 http://127.0.0.1:8090/v1/models | grep -q qwen3; then
    echo "ABORT: no qwen3 server on 8090"; exit 1
fi

command cp -f "$REPO/app/config.json" "$BACKUP"
"$PY" - <<'PYEOF'
import json
p = "/home/fakemitch/pinokio/api/alexandria-audiobook2.git/app/config.json"
d = json.load(open(p, encoding="utf-8"))
for key in ("llm", "llm_local"):
    if isinstance(d.get(key), dict):
        d[key]["model_name"] = "qwen3-14b"
json.dump(d, open(p, "w", encoding="utf-8"), indent=2)
print("config -> qwen3-14b")
PYEOF

echo ""
echo "=== grimgar03 on the current pipeline  $(date -u +%FT%TZ) ==="
"$PY" -u generate_script.py \
    "$REPO/ab_test_runtime/results/collect_all_20260722-155801/inputs/grimgar03.txt" \
    --output "$OUT/grimgar03_regression.json" > "$L/regression_grimgar03.log" 2>&1
echo "  rc=$?"
grep -E "Stripped publisher|Split into" "$L/regression_grimgar03.log" | sed 's/^/  /'
echo "  chunks completed : $(grep -c 'Got .* entries' "$L/regression_grimgar03.log")"
echo "  retries          : $(grep -c 'failed quality validation' "$L/regression_grimgar03.log")"
echo "  book written     : $([ -f "$OUT/grimgar03_regression.json" ] && echo yes || echo NO)"
echo ""
echo "  BASELINE 2026-08-09 (pipeline before the changes): 49/49 chunks, 100%"
echo "REGRESSION RUN DONE $(date -u +%FT%TZ)"
