"""Native cast/version dialogs preserve cancellation and async ownership."""
from pathlib import Path
import subprocess
import unittest

SOURCE=Path(__file__).resolve().parent.parent/'static/js/app-core.js'
class VoiceTextDialogJsTests(unittest.TestCase):
    def test_native_cast_and_version_admission_and_late_selections(self):
        code=r'''
const fs=require('fs'),vm=require('vm'),assert=require('assert'),s=fs.readFileSync(process.argv[1],'utf8');let value=null,posts=[],loads=0,castLoads=0,options,resolve;const card={dataset:{voice:'A 日本語/#'},isConnected:true},button={disabled:false,closest:()=>card};const c={currentBookFilename:'book-A',flushVoiceSaves:async()=>{},showPresetEditor:async o=>{options=o;return value;},API:{post:async(path,data)=>{posts.push({path,data});}},loadVoices:async()=>loads++,loadCastLibrary:async()=>castLoads++,setCastStatus:()=>{},showToast:()=>{},escapeHtml:String};c.window=c;vm.createContext(c);vm.runInContext(s.slice(s.indexOf('function getVoiceCardMetadata('),s.indexOf('function createVoiceCard(')),c);vm.runInContext(s.slice(s.indexOf('function showActionError('),s.indexOf('function showConfirm(')),c);let a=s.indexOf('window.addVoiceVersion =');vm.runInContext(s.slice(a,s.indexOf('window.saveNarratorStrategy =',a)),c);a=s.indexOf('async function createCast()');vm.runInContext(s.slice(a,s.indexOf('async function deleteCast()',a)),c);let finished=false;process.on('beforeExit',()=>assert(finished));
(async()=>{await c.addVoiceVersion(button);await c.createCast();assert.strictEqual(posts.length,0);assert(!button.disabled);assert.strictEqual(options.nameLabel,'Cast name');value={name:'teen',description:''};c.showPresetEditor=async o=>{options=o;c.currentBookFilename='book-B';return value;};await c.addVoiceVersion(button);assert.strictEqual(posts.length,0);assert(!button.disabled);assert.strictEqual(options.description,'adult');assert.strictEqual(options.descriptionLabel,'Age group');c.currentBookFilename='book-A';c.showPresetEditor=async()=>value;await c.addVoiceVersion(button);assert.strictEqual(posts[0].path,'/api/voices/'+encodeURIComponent(card.dataset.voice)+'/versions');assert.strictEqual(posts[0].data.age_group,'adult');assert.strictEqual(loads,1);
c.API.post=(path,data)=>{posts.push({path,data});return new Promise(r=>resolve=r);};const pending=c.addVoiceVersion(button);await new Promise(setImmediate);const count=posts.length;await c.addVoiceVersion(button);assert.strictEqual(posts.length,count);c.currentBookFilename='book-C';resolve({});await pending;assert(!button.disabled);assert.strictEqual(loads,1,'old acknowledgement cannot refresh new book');
c._selectedCast='original';c.showPresetEditor=async()=>{c._selectedCast='changed';return{name:'new cast'};};const before=posts.length;await c.createCast();assert.strictEqual(posts.length,before);c._selectedCast='original';c.showPresetEditor=async()=>({name:'new cast'});const creating=c.createCast();await new Promise(setImmediate);c._selectedCast='later selection';resolve({});await creating;assert.strictEqual(c._selectedCast,'later selection');assert.strictEqual(castLoads,0);
c.API.post=async(path,data)=>posts.push({path,data});await c.createCast();assert.strictEqual(c._selectedCast,'new cast');assert.strictEqual(castLoads,1);c.API.post=async()=>{throw Error('refused');};await c.addVoiceVersion(button);assert(!button.disabled);finished=true;})().catch(e=>{console.error(e);process.exitCode=1;});
'''
        out=subprocess.run(['node','-e',code,str(SOURCE)],capture_output=True,text=True,timeout=15)
        self.assertEqual(out.returncode,0,out.stderr)

    def test_age_dialog_cancel_duplicate_and_changed_target_refusal(self):
        code=r'''
const fs=require('fs'),vm=require('vm'),assert=require('assert'),s=fs.readFileSync(process.argv[1],'utf8');let values=null,options,posts=[],polls=0,confirmCalls=0,confirmResult=true,resolveDialog,resolveCost;const card={dataset:{voice:'Alice 日本語/#'},isConnected:true},button={disabled:false,closest:()=>card};const c={currentBookFilename:'book-A',showPresetEditor:async o=>{options=o;return values;},confirmIfRemote:async()=>{confirmCalls++;return confirmResult;},API:{post:async(path,data)=>posts.push({path,data})},pollPersonaStatus:()=>polls++,getPersonaContextLines:()=>37,showToast:()=>{}};c.window=c;vm.createContext(c);vm.runInContext(s.slice(s.indexOf('function getVoiceCardMetadata('),s.indexOf('function createVoiceCard(')),c);vm.runInContext(s.slice(s.indexOf('function showActionError('),s.indexOf('function showConfirm(')),c);const a=s.indexOf('window.generateAgeVersion =');vm.runInContext(s.slice(a,s.indexOf('window.selectVoiceCandidate =',a)),c);let finished=false;process.on('beforeExit',()=>assert(finished));
(async()=>{
 await c.generateAgeVersion(button,'elderly');assert.strictEqual(options.name,'elderly');assert.strictEqual(options.nameLabel,'Age profile');assert.strictEqual(options.actionLabel,'Generate age version');assert.strictEqual(options.includeDescription,false);assert.strictEqual(posts.length,0);assert.strictEqual(confirmCalls,0);assert(!button.disabled);
 c.showPresetEditor=o=>new Promise(r=>resolveDialog=r);const pending=c.generateAgeVersion(button);assert(button.disabled);await c.generateAgeVersion(button);c.currentBookFilename='book-B';resolveDialog({name:'teen'});await pending;assert.strictEqual(posts.length,0);assert.strictEqual(confirmCalls,0);assert(!button.disabled);
 c.showPresetEditor=async()=>({name:'teen'});c.currentBookFilename='book-A';c.confirmIfRemote=()=>new Promise(r=>resolveCost=r);const costPending=c.generateAgeVersion(button);await new Promise(setImmediate);card.dataset.voice='Bob';resolveCost(true);await costPending;assert.strictEqual(posts.length,0);assert(!button.disabled);
 card.dataset.voice='Alice 日本語/#';card.isConnected=false;c.confirmIfRemote=async()=>true;await c.generateAgeVersion(button);assert.strictEqual(posts.length,0);card.isConnected=true;c.confirmIfRemote=async()=>false;await c.generateAgeVersion(button);assert.strictEqual(posts.length,0);
 c.confirmIfRemote=async()=>true;await c.generateAgeVersion(button);assert.strictEqual(posts.length,1);assert.strictEqual(posts[0].path,'/api/generate_personas');assert.deepStrictEqual(JSON.parse(JSON.stringify(posts[0].data)),{speaker:'Alice 日本語/#',age_group:'teen',advanced:false,context_lines:37});assert.strictEqual(polls,1);assert(!button.disabled);
 c.API.post=async()=>{throw Error('refused');};await c.generateAgeVersion(button);assert.strictEqual(polls,1);assert(!button.disabled);finished=true;
})().catch(e=>{console.error(e);process.exitCode=1;});
'''
        out=subprocess.run(['node','-e',code,str(SOURCE)],capture_output=True,text=True,timeout=15)
        self.assertEqual(out.returncode,0,out.stderr)

    def test_audit_and_style_dialogs_preserve_blank_values_and_ownership(self):
        code=r'''
const fs=require('fs'),vm=require('vm'),assert=require('assert'),s=fs.readFileSync(process.argv[1],'utf8');let values=null,options,posts=[],loads=0,resolve,selected='Alice/#';const card={dataset:{voice:'Alice/#'},isConnected:true},button={disabled:false,closest:()=>card},row={isConnected:true,querySelector:()=>({value:selected})};const c={currentBookFilename:'book-A',document:{querySelector:()=>row},showPresetEditor:async o=>{options=o;return values;},API:{post:async(path,data)=>posts.push({path,data})},loadVoices:async()=>loads++,showToast:()=>{},_voicesByName:{'Alice/#':{config:{persona_voice_audit:{suggestion_reason:'old reason',voice_adapter_id:'old adapter',persona_ref:'ref'}}}}};c.window=c;vm.createContext(c);vm.runInContext(s.slice(s.indexOf('function getVoiceCardMetadata('),s.indexOf('function createVoiceCard(')),c);vm.runInContext(s.slice(s.indexOf('function showActionError('),s.indexOf('function showConfirm(')),c);for(const [start,end]of[['window.editPersonaVoiceAudit =','window.regeneratePersona ='],['async function voiceChangesHere(','function collectVoiceConfig()']]){const a=s.indexOf(start);vm.runInContext(s.slice(a,s.indexOf(end,a)),c);}let finished=false;process.on('beforeExit',()=>assert(finished));
(async()=>{
 await c.editPersonaVoiceAudit(button);assert.strictEqual(posts.length,0);assert(options.allowEmptyName);assert.strictEqual(options.name,'old reason');assert.strictEqual(options.description,'old adapter');assert(!button.disabled);await c.voiceChangesHere(2);assert.strictEqual(posts.length,0);assert(options.allowEmptyName);assert.strictEqual(options.actionLabel,'Save change point');
 c.showPresetEditor=()=>new Promise(r=>resolve=r);let pending=c.editPersonaVoiceAudit(button);assert(button.disabled);await c.editPersonaVoiceAudit(button);c.currentBookFilename='book-B';resolve({name:'changed',description:'new'});await pending;assert.strictEqual(posts.length,0);assert(!button.disabled);
 c.currentBookFilename='book-A';pending=c.voiceChangesHere(2);selected='Bob';resolve({name:'new style'});await pending;assert.strictEqual(posts.length,0);selected='Alice/#';pending=c.voiceChangesHere(2);row.isConnected=false;resolve({name:'new style'});await pending;assert.strictEqual(posts.length,0);row.isConnected=true;
 c.showPresetEditor=async()=>({name:'',description:''});await c.editPersonaVoiceAudit(button);assert.strictEqual(posts[0].path,'/api/voices/Alice%2F%23/persona-voice-audit');assert.strictEqual(posts[0].data.suggestion_reason,'');assert.strictEqual(posts[0].data.voice_adapter_id,'');assert.strictEqual(posts[0].data.persona_ref,'ref');await c.voiceChangesHere(2);assert.strictEqual(posts[1].path,'/api/voices/Alice%2F%23/style_timeline');assert.strictEqual(posts[1].data.character_style,'');assert.strictEqual(posts[1].data.from_index,2);assert.strictEqual(loads,2);
 c.API.post=()=>new Promise(r=>resolve=r);pending=c.editPersonaVoiceAudit(button);await new Promise(setImmediate);c.currentBookFilename='book-C';resolve({});await pending;assert.strictEqual(loads,2);assert(!button.disabled);
 c.API.post=async()=>{throw Error('refused');};await c.editPersonaVoiceAudit(button);assert(!button.disabled);assert.strictEqual(loads,2);finished=true;
})().catch(e=>{console.error(e);process.exitCode=1;});
'''
        out=subprocess.run(['node','-e',code,str(SOURCE)],capture_output=True,text=True,timeout=15)
        self.assertEqual(out.returncode,0,out.stderr)
