"""Clipboard refusal preserves exact text and does not claim success."""
from pathlib import Path
import subprocess
import unittest

class ClipboardFallbackJsTests(unittest.TestCase):
    def test_manual_copy_preserves_text_and_cleans_up(self):
        source=Path(__file__).resolve().parent.parent/'static/js/app-core.js'
        code=r'''const fs=require('fs'),vm=require('vm'),assert=require('assert');const s=fs.readFileSync(process.argv[1],'utf8');const es={};const el=id=>es[id]||(es[id]={value:'',style:{},ls:{},setAttribute(){},focus(){this.focused=true},select(){this.selected=true},addEventListener(n,f){this.ls[n]=f},removeEventListener(n){delete this.ls[n]}});let modern=true,legacy=false,notices=[],shown=[],delayShown=false,hides=0;const c={navigator:{clipboard:{writeText:async()=>{if(!modern)throw Error('denied')}}},document:{getElementById:el,createElement:()=>el('temporary'),body:{appendChild(){},removeChild(){}},execCommand:()=>legacy},showToast:(...a)=>notices.push(a),bootstrap:{Modal:class{constructor(e){this.e=e}show(){shown.push(el('manual-copy-text').value);if(!delayShown)this.e.ls['shown.bs.modal']()}hide(){hides++;this.e.ls['hidden.bs.modal']()}dispose(){}}}};c.window={prompt:()=>null};vm.createContext(c);vm.runInContext('let confirmQueue=Promise.resolve();'+s.slice(s.indexOf('function showManualCopy('),s.indexOf('function escapeHtml(')),c);let done=false;process.on('beforeExit',()=>assert(done));(async()=>{assert(await c.copyToClipboard('modern'));modern=false;legacy=true;assert(await c.copyToClipboard('legacy'));legacy=false;const text='  café 日本語\n<unsafe>  ';const a=c.copyToClipboard(text,'Prompt');await new Promise(setImmediate);assert.strictEqual(el('manual-copy-text').value,text);assert(el('manual-copy-text').selected&&el('manual-copy-text').focused);const b=c.copyToClipboard('second');await new Promise(setImmediate);assert.strictEqual(shown.length,1);el('manual-copy-close').ls.click();assert.strictEqual(await a,false);await new Promise(setImmediate);assert.strictEqual(shown[1],'second');el('manual-copy-close').ls.click();assert.strictEqual(await b,false);assert.strictEqual(el('manual-copy-text').value,'');assert.strictEqual(notices.length,2);delayShown=true;const early=c.copyToClipboard('early');await new Promise(setImmediate);el('manual-copy-close').ls.click();assert.strictEqual(hides,2,'must wait until shown');el('manualCopyModal').ls['shown.bs.modal']();assert.strictEqual(await early,false);assert.strictEqual(hides,3);assert.strictEqual(el('manual-copy-text').value,'');done=true})().catch(e=>{console.error(e);process.exitCode=1});'''
        result=subprocess.run(['node','-e',code,str(source)],capture_output=True,text=True,timeout=15)
        self.assertEqual(result.returncode,0,result.stderr)
